[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "kitab"
version = "0.2.0"
description = "A simple and lightweight word processor written in qt. معالج نصوص بسيط وخفيف مكتوب بمكتبة qt."
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "GPL-3.0-or-later"
license-files = ["LICEN[CS]E*"]
dependencies = [
    "pyside6-essentials==6.11.1",
]

[project.urls]
Homepage = "https://github.com/abdulrahman-103/Kitab"
Issues = "https://github.com/abdulrahman-103/Kitab/issues"

[project.gui-scripts]
kitab = "main:main"

[tool.hatch.build.targets.wheel]
packages = ["src/kitab"]
